# Site settings
title: Audrey Penven
email: audrey@audreypenven.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://audreypenven.net" # the base hostname & protocol for your site
twitter_username: yerdua
github_username:  yerdua

# Build settings
markdown: kramdown

